version: '3.8'
services:
  db:
    container_name: web-chat-db
    image: 'postgres:14.5-alpine'
    restart: always
    tty: true
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chat
    ports:
      - '5432:5432'
    volumes:
      - './data:/var/lib/postgres/data'
      - './data/init.sql:/docker-entrypoint-initdb.d/init.sql'
    networks:
      - web_chat
  api:
    build: .
    container_name: web-chat-backend
    volumes:
      - './:/app/'
    tty: true
    ports:
      - '3333:3333'
    depends_on:
      - db
    links:
      - db
    networks:
      - web_chat
volumes:
  data:
    driver: local
networks:
  web_chat:
    driver: bridge

